"""empty message

Revision ID: 0112cddac42c
Revises: a200f6ef816f
Create Date: 2023-06-12 18:00:46.040518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0112cddac42c'
down_revision = 'a200f6ef816f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
