"""empty message

Revision ID: 49f4af1ec267
Revises: 
Create Date: 2023-06-30 00:06:38.538919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f4af1ec267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('image', sa.String(length=10000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ingredients', sa.String(length=500), nullable=False),
    sa.Column('dietary_preferences', sa.String(length=500), nullable=True),
    sa.Column('allergen', sa.String(length=500), nullable=True),
    sa.Column('estimated_time', sa.String(length=100), nullable=False),
    sa.Column('quantity_available', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item')
    op.drop_table('user')
    # ### end Alembic commands ###
